---
- name: Add repository key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.2.asc
    state: present
  tags: install

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Apt update
  ansible.builtin.apt:
    cache_valid_time: 300
    update_cache: true
  tags: install

- name: Apt upgrade
  ansible.builtin.apt:
    upgrade: full
  tags: install

- name: Install MongoDB
  ansible.builtin.apt:
    name: mongodb-org
    state: present
  tags: install

- name: Enable mongod
  ansible.builtin.systemd:
    name: mongod
    daemon_reload: true
    enabled: true
  tags: install
