---
# tasks file for db
- name: Show info about the env this host belongs to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment"
- name: Install MongoDB 3.2
  ansible.builtin.include_tasks: install_mongo.yml
  args:
    apply:
      become: true
- name: Configure MongoDB
  ansible.builtin.include_tasks: config_mongo.yml
