---
# tasks file for db
- name: Show info about the env this host belongs to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment"
- name: Install MongoDB 3.2
  ansible.builtin.include: install_mongo.yml
- name: Configure MongoDB
  ansible.builtin.include: config_mongo.yml
