---
- name: Deploy app
  hosts: tag_reddit-app
  tasks:
    - name: Fetch the latest version of application code
      ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: Reload puma
    - name: Bundle install
      community.general.bundler:
        state: present
        chdir: /home/appuser/reddit
  handlers:
    - name: Reload puma
      become: true
      ansible.builtin.systemd:
        name: monapp
        state: restarted
        daemon_reload: true
