- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
    - name: Add repository key
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present

    - name: Add MongoDB repository
      ansible.builtin.apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Apt upgrade
      ansible.builtin.apt:
        upgrade: full

    - name: Install MongoDB
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: Enable mongod
      ansible.builtin.systemd:
        name: mongod
        daemon_reload: true
        enabled: true
