---
# tasks file for app
- name: Show info about the env this host belongs to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Install Ruby and build-essential
  ansible.builtin.include: ruby.yml
- name: Install Puma
  ansible.builtin.include: puma.yml
