---
- name: Add unit file for Puma
  ansible.builtin.template:
    src: monapp.service.j2
    dest: /etc/systemd/system/monapp.service
    # mode: 0660
  notify: Reload puma

- name: Add config for DB connection
  ansible.builtin.template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Enable Puma
  ansible.builtin.systemd:
    name: monapp
    enabled: true
    daemon_reload: true
