---
- name: Configure hosts & deply application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.166.0.22
  tasks:

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag

    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/monapp.service
        dest: /etc/systemd/system/monapp.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags: app-tag

    - name: enable puma
      become: true
      systemd:
        name: monapp
        enabled: true
      tags: app-tag

  handlers:
    - name: restart mongod
      become: true
      systemd:
        name: mongod
        state: restarted
        daemon_reload: true

    - name: reload puma
      become: true
      systemd:
        name: monapp
        state: restarted
        daemon_reload: true
