Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
      v.memory = 512
    end
  
    config.vm.define "tag_reddit-db" do |db|
      db.vm.box = "ubuntu/bionic64"
      db.vm.hostname = "dbserver"
      db.vm.network :private_network, ip: "192.168.56.10"
      
      db.vm.provision "ansible" do |ansible|
        
        ansible.playbook = "playbooks/site.yml"
        ansible.groups = {
          "db" => ["tag_reddit-db"],
          "db:vars" => { "mongo_bind_ip" => "0.0.0.0" },
        }
        end
    end
    
    config.vm.define "tag_reddit-app" do |app|
      app.vm.box = "ubuntu/bionic64"
      app.vm.hostname = "appserver"
      app.vm.network :private_network, ip: "192.168.56.20"
      app.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbooks/site.yml"
        ansible.groups = {
          "app" => ["tag_reddit-app"],
          "app:vars" => {"db_host" => "192.168.56.10"},
        }
        ansible.extra_vars = {
          "deploy_user" => "ubuntu"
        }
        end
    end
  end
