name: Slack Notification

on:
  workflow_run:
    workflows: [Devops study homework tests]
    types: [completed]

jobs:
  slack-notify:
    name: Build status
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ github.event.workflow_run.conclusion }}
